{
 "title": "JWT PIZZA SERVICE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "direction": "backward" },
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_revenue_mBTC_total{job=\"jwt-pizza-service\"}[1m]) *60",
     "legendFormat": "Pizza Revenue"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "service_latency_milliseconds{job=\"jwt-pizza-service\"}",
     "legendFormat": "service endpoint "
    },
    {
     "expr": "pizza_creation_latency_milliseconds{job=\"jwt-pizza-service\"}",
     "legendFormat": "pizza creation ms"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{job=\"jwt-pizza-service\"}[1m]) *60",
     "legendFormat": "Sold/min"
    },
    {
     "expr": "rate(pizza_failures_total{job=\"jwt-pizza-service\"}[1m]) * 60 ",
     "legendFormat": "creation failures / min"
    },
    { "legendFormat": "revenue/min" }
   ]
  },
  {
   "title": "CPU and Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{job=\"jwt-pizza-service\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "memory_usage_percent{job=\"jwt-pizza-service\"}",
     "legendFormat": "Memory %"
    }
   ]
  },
  {
   "title": "Authentication Attemps/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": " rate(auth_successful_total{job=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(auth_failed_total{job=\"jwt-pizza-service\"}[1m]) * 60 ",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_users{job=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(http_requests_get_total{job=\"jwt-pizza-service\"}[1m]) * 60   ",
     "legendFormat": "GET"
    },
    {
     "expr": " rate(http_requests_post_total{job=\"jwt-pizza-service\"}[1m]) * 60  ",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_requests_put_total{job=\"jwt-pizza-service\"}[1m]) * 60  ",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(http_requests_delete_total{job=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}